/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.management.system;

import com.itextpdf.text.log.Logger;
import dao.DbOperations;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.System.Logger.Level;
import java.net.Socket;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.User;
import org.json.simple.JSONObject;

/**
 *
 * @author khaled
 */
public class Home extends javax.swing.JFrame {
    
    public String email;
    public String balance1;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String useremail) {
        
        initComponents();
        email=useremail;
        if(!email.equals("admin1@gmail.com")){
            btnCategory.setVisible(false);
            btnNewProduct.setVisible(false);
            btnEditProduct.setVisible(false);
            btnVerifyuser.setVisible(false);
            
            //balanceValue.setText(balance);
        }
        if(email.equals("admin1@gmail.com")){
            btnLogout.setVisible(false);
            
            try{
            ResultSet rs = DbOperations.getData("select wallet from user where email='admin1@gmail.com'");
            while(rs.next())
            {
                
                balanceTxt.setText(rs.getString("wallet"));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
            
            
        }
    }
    
    
    public Home(String useremail, String balance) {
        
        initComponents();
        email=useremail;
        this.balance1=balance;
       
            btnCategory.setVisible(false);
            btnNewProduct.setVisible(false);
            btnEditProduct.setVisible(false);
            btnVerifyuser.setVisible(false);
            
            balanceTxt.setText(balance);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnAddBalance = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnViewBill = new javax.swing.JButton();
        btnChangeQ = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        btnVerifyuser = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        aa = new javax.swing.JLabel();
        balanceTxt = new javax.swing.JLabel();
        addbalance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddBalance.setText("ADD Balance");
        btnAddBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBalanceActionPerformed(evt);
            }
        });

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnViewBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewBill.setText("View Bill & Order Details");
        btnViewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillActionPerformed(evt);
            }
        });

        btnChangeQ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChangeQ.setText("Change Security Question");
        btnChangeQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeQActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCategory.setText("Manage Category");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnNewProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });

        btnVerifyuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerifyuser.setText("Verify User");
        btnVerifyuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyuserActionPerformed(evt);
            }
        });

        btnEditProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditProduct.setText("View,Edit,Delete Product");
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        aa.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        aa.setText("Balance");

        balanceTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButton1.setText("Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddBalance)
                                    .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLogout)
                                        .addGap(77, 77, 77)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPlaceOrder)
                                        .addGap(61, 61, 61)
                                        .addComponent(btnViewBill))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(btnNewProduct)
                                        .addGap(76, 76, 76)
                                        .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnChangeQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnVerifyuser)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343)))
                .addGap(259, 259, 259)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnPlaceOrder)
                    .addComponent(btnViewBill)
                    .addComponent(btnChangeQ)
                    .addComponent(btnExit)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBalance)
                    .addComponent(addbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewProduct)
                    .addComponent(btnCategory)
                    .addComponent(btnVerifyuser)
                    .addComponent(btnEditProduct))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBalanceActionPerformed
        // TODO add your handling code here:
        String reqBalance = addbalance.getText();
        
            final String HOST = LoginClient.HOST;
            final int PORT = 4040;
            JSONObject obj = new JSONObject();          
            obj.put("type", "addbalance");
            obj.put("balance", reqBalance);
            obj.put("email", email);
           

            try (
                 Socket socket = new Socket(HOST, PORT);  PrintWriter out = new PrintWriter(socket.getOutputStream(), true);  Scanner in = new Scanner(socket.getInputStream());) {
                out.println(obj.toString());
                System.out.println(obj.toString());
                
                balanceTxt.setText(String.valueOf(Integer.parseInt(balance1)+Integer.parseInt(reqBalance)));
                balance1 = String.valueOf(Integer.parseInt(balance1)+Integer.parseInt(reqBalance));
                

                

            } catch (IOException ex) {
                
            }
        
        
    }//GEN-LAST:event_btnAddBalanceActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
     int a = JOptionPane.showConfirmDialog(null, "Do you realy want to Exit?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0){
        System.exit(0);
     }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangeQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeQActionPerformed

    private void btnViewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnViewBillActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
     int a = JOptionPane.showConfirmDialog(null, "Do you realy want to logout?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0){
         setVisible(false);
         new LoginClient().setVisible(true);
     } 
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
        
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // TODO add your handling code here:
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnVerifyuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyuserActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnVerifyuserActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email,balance1).setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Info(email).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line argument
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JTextField addbalance;
    private javax.swing.JLabel balanceTxt;
    private javax.swing.JButton btnAddBalance;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnChangeQ;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnVerifyuser;
    private javax.swing.JButton btnViewBill;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
